// ════════════════════════════════════════════════════════════════════════════
// comisiones.js — Reglas, cálculo, aprobación y trazabilidad comercial
// ════════════════════════════════════════════════════════════════════════════

let _comTab='resumen';
let _comState={sellers:[],runs:[],dashboard:null};
let _comQuery='';
let _comStatus='todos';

function _comEsc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function _comMoney(value){return typeof fmt==='function'?fmt(Number(value)||0):`RD$${(Number(value)||0).toFixed(2)}`;}
function _comToday(){if(typeof today==='function')return today();const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function _comMonthStart(){return _comToday().slice(0,8)+'01';}
function _comInitials(name){return String(name||'C').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();}
function _comBadge(status){const cls=['aprobado','pagado'].includes(status)?'g':status==='borrador'?'a':'n';return `<span class="badge ${cls}">${_comEsc(status||'')}</span>`;}
function _comMode(s){if(s.commission_mode==='percent_sales')return `${Number(s.commission_rate||0)}% de venta neta`;if(s.commission_mode==='percent_margin')return `${Number(s.commission_rate||0)}% del margen`;if(s.commission_mode==='fixed_sale')return `${_comMoney(s.commission_fixed)} por venta`;return 'Sin comisión';}
function _comFrequency(value){return value==='semanal'?'Semanal':value==='quincenal'?'Quincenal':'Mensual';}
function _comEmpty(icon,title,text,action='',handler=''){return `<div class="ven-empty"><div class="ven-empty-icon">${svg(icon)}</div><h3>${_comEsc(title)}</h3><p>${_comEsc(text)}</p>${action?`<button class="btn btn-green btn-sm" onclick="${handler}">${svg('plus')} ${_comEsc(action)}</button>`:''}</div>`;}

async function renderComisiones(el){
  if(!['admin','superadmin'].includes(user?.role)){routeTo('dash');return;}
  el.innerHTML=`<div class="com-shell"><section class="ven-panel">${_comEmpty('clock','Preparando Comisiones','Calculando reglas, ventas y liquidaciones…')}</section></div>`;
  const [sellers,runs,dashboard]=await Promise.all([
    window.api.salespeople.getAll({}),window.api.salespeople.getCommissionRuns({}),window.api.salespeople.getDashboard({from:_comMonthStart(),to:_comToday()}),
  ]);
  _comState={sellers:sellers?.data||[],runs:runs?.data||[],dashboard:dashboard?.data||null};_comRender(el);
}

function _comSetTab(tab){_comTab=tab;_comQuery='';_comStatus='todos';_comRender();}

function _comRender(el=document.getElementById('page')){
  if(!el)return;const drafts=_comState.runs.filter(x=>x.status==='borrador').length,approved=_comState.runs.filter(x=>x.status==='aprobado').length;
  const tabs=[['resumen','grid','Resumen',''],['liquidaciones','list','Liquidaciones',_comState.runs.length],['reglas','settings','Reglas',_comState.sellers.filter(x=>x.status==='activo').length],['flujo','trend','Flujo',drafts+approved]];
  el.innerHTML=`<div class="com-shell"><section class="com-hero"><div class="com-hero-main"><div><div class="com-eyebrow"><span></span> Gestión de incentivos comerciales</div><h1>Comisiones</h1><p>Define reglas, calcula ventas comisionables y aprueba liquidaciones antes de enviarlas a Nómina.</p></div><div class="com-actions"><button class="btn btn-out" onclick="routeTo('vendedores')">${svg('users')} Ver vendedores</button><button class="btn btn-green" onclick="comisionesOpenCalculation()">${svg('plus')} Calcular comisión</button></div></div><div class="com-hero-foot"><span>${svg('trend')} Las devoluciones se descuentan automáticamente</span><span>${svg('check')} Solo las liquidaciones aprobadas llegan a Nómina</span></div></section>
    <nav class="com-nav">${tabs.map(([key,icon,label,count])=>`<button class="com-nav-btn ${_comTab===key?'on':''}" onclick="_comSetTab('${key}')">${svg(icon)}<span>${label}</span>${count!==''?`<b>${count}</b>`:''}</button>`).join('')}</nav><div id="com-content"></div></div>`;
  const content=document.getElementById('com-content');if(_comTab==='resumen')_comRenderSummary(content);if(_comTab==='liquidaciones')_comRenderRuns(content);if(_comTab==='reglas')_comRenderRules(content);if(_comTab==='flujo')_comRenderFlow(content);
}

function _comTotals(status){return _comState.runs.filter(x=>x.status===status).reduce((sum,x)=>sum+Number(x.commission_total||0),0);}
function _comRenderSummary(el){
  const dashboard=_comState.dashboard||{commissionTotal:0,rows:[]},drafts=_comState.runs.filter(x=>x.status==='borrador'),approved=_comState.runs.filter(x=>x.status==='aprobado'),paid=_comState.runs.filter(x=>x.status==='pagado');
  const metric=(tone,icon,label,value,note)=>`<article class="com-metric"><div class="com-metric-icon ${tone}">${svg(icon)}</div><div><label>${label}</label><strong>${value}</strong><span>${note}</span></div></article>`;
  const sellers=(dashboard.rows||[]).filter(x=>Number(x.commission)>0).sort((a,b)=>Number(b.commission)-Number(a.commission)).slice(0,5);
  el.innerHTML=`<div class="com-metrics">${metric('blue','trend','Estimado del período',_comMoney(dashboard.commissionTotal),`${dashboard.rows?.length||0} vendedores evaluados`)}${metric('amber','clock','Por revisar',_comMoney(_comTotals('borrador')),`${drafts.length} liquidaciones en borrador`)}${metric('purple','check','Disponible para Nómina',_comMoney(_comTotals('aprobado')),`${approved.length} liquidaciones aprobadas`)}${metric('green','cash','Pagado',_comMoney(_comTotals('pagado')),`${paid.length} liquidaciones cerradas`)}</div>
    <div class="com-dashboard-grid"><section class="ven-panel"><div class="ven-panel-head"><div><div class="ven-panel-title">${svg('chart')} Proyección por vendedor</div><div class="ven-panel-sub">Estimación comercial antes de crear y aprobar el corte</div></div><button class="btn btn-out btn-sm" onclick="_comSetTab('reglas')">Revisar reglas</button></div>${sellers.length?`<div class="com-ranking">${sellers.map((row,index)=>`<button onclick="comisionesOpenCalculation(${row.id})"><i>${index+1}</i><span class="ven-avatar ${row.type==='ambulante'?'street':''}">${_comInitials(row.name)}</span><div><strong>${_comEsc(row.name)}</strong><small>${row.salesCount} operaciones · ventas ${_comMoney(row.sales)}</small></div><b>${_comMoney(row.commission)}</b></button>`).join('')}</div>`:_comEmpty('trend','Sin comisión proyectada','Configura una regla y registra ventas para obtener una estimación.')}</section>
    <aside class="ven-panel"><div class="ven-panel-head"><div><div class="ven-panel-title">${svg('trend')} Flujo correcto</div><div class="ven-panel-sub">Comisiones y Nómina permanecen separadas</div></div></div><div class="com-process"><div><i>1</i><span><strong>Regla comercial</strong><small>Porcentaje de venta, margen o monto fijo.</small></span></div><div><i>2</i><span><strong>Liquidación</strong><small>Congela ventas, devoluciones y período.</small></span></div><div><i>3</i><span><strong>Aprobación</strong><small>Convierte el cálculo en obligación pagable.</small></span></div><div><i>4</i><span><strong>Nómina</strong><small>La incorpora al pago sin recalcularla.</small></span></div></div><button class="btn btn-out btn-fw" onclick="routeTo('nomina')">Abrir módulo Nómina →</button></aside></div>`;
}

function _comFilteredRuns(){return _comState.runs.filter(r=>(_comStatus==='todos'||r.status===_comStatus)&&(!_comQuery||`${r.salesperson_name} ${r.date_from} ${r.date_to} ${r.status}`.toLowerCase().includes(_comQuery.toLowerCase())));}
function _comRunsTable(rows){return `<div class="tw"><table><thead><tr><th>Período</th><th>Vendedor</th><th>Regla congelada</th><th style="text-align:center">Ventas</th><th style="text-align:right">Base ventas</th><th style="text-align:right">Comisión</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr class="ven-click-row" onclick="comisionesView(${r.id})"><td><strong>${_comEsc(r.date_from)}</strong><div class="ven-person-meta">al ${_comEsc(r.date_to)} · ${_comFrequency(r.frequency)}</div></td><td><div class="ven-person"><div class="ven-avatar ${r.seller_type==='ambulante'?'street':''}">${_comInitials(r.salesperson_name)}</div><div class="ven-person-name">${_comEsc(r.salesperson_name)}</div></div></td><td>${_comEsc(String(r.calculation_mode||'').replaceAll('_',' '))}${r.rate?`<div class="ven-person-meta">${r.rate}%</div>`:''}</td><td style="text-align:center"><strong>${r.sales_count}</strong></td><td style="text-align:right" class="ven-money">${_comMoney(r.sales_total)}</td><td style="text-align:right;font-weight:850;color:#7c3aed" class="ven-money">${_comMoney(r.commission_total)}</td><td>${_comBadge(r.status)}</td><td onclick="event.stopPropagation()"><div class="flex">${r.status==='borrador'?`<button class="btn btn-green btn-sm" onclick="comisionesApprove(${r.id})">Aprobar</button>`:''}<button class="btn btn-ghost btn-sm" onclick="comisionesView(${r.id})">${svg('eye')}</button></div></td></tr>`).join('')}</tbody></table></div>`;}

function _comRenderRuns(el){const rows=_comFilteredRuns(),filter=`<select class="inp" style="width:155px" onchange="_comStatus=this.value;_comRenderRuns(document.getElementById('com-content'))"><option value="todos">Todos los estados</option>${['borrador','aprobado','pagado'].map(x=>`<option value="${x}" ${_comStatus===x?'selected':''}>${x}</option>`).join('')}</select>`;el.innerHTML=`<section class="ven-panel"><div class="ven-panel-head"><div><div class="ven-panel-title">${svg('list')} Liquidaciones de comisión</div><div class="ven-panel-sub">Documentos comerciales auditables, independientes de los períodos de nómina</div></div><button class="btn btn-green btn-sm" onclick="comisionesOpenCalculation()">${svg('plus')} Nuevo cálculo</button></div><div class="ven-panel-body"><div class="ven-toolbar"><div class="ven-search">${svg('search')}<input value="${_comEsc(_comQuery)}" oninput="_comQuery=this.value;_comRenderRuns(document.getElementById('com-content'))" placeholder="Buscar vendedor o período…"/></div>${filter}</div></div>${rows.length?_comRunsTable(rows):_comEmpty('trend','No hay liquidaciones para mostrar','Calcula la primera comisión o cambia los filtros.','Calcular comisión','comisionesOpenCalculation()')}</section>`;}

function _comRenderRules(el){const sellers=_comState.sellers.filter(s=>s.status==='activo'&&(!_comQuery||`${s.name} ${s.code} ${s.seller_type}`.toLowerCase().includes(_comQuery.toLowerCase()))),cards=sellers.map(s=>`<article class="com-rule-card"><div class="com-rule-head"><div class="ven-person"><div class="ven-avatar ${s.seller_type==='ambulante'?'street':''}">${_comInitials(s.name)}</div><div><div class="ven-person-name">${_comEsc(s.name)}</div><div class="ven-person-meta">${_comEsc(s.code)} · ${s.seller_type==='ambulante'?'Ambulante':'Fijo'}</div></div></div><span class="badge ${s.commission_mode==='none'?'n':'g'}">${s.commission_mode==='none'?'Sin comisión':'Activa'}</span></div><div class="com-rule-values"><div><label>Regla</label><strong>${_comEsc(_comMode(s))}</strong></div><div><label>Frecuencia del corte</label><strong>${_comFrequency(s.commission_frequency)}</strong></div></div><div class="com-rule-foot"><span>La regla se congela al crear cada liquidación.</span><button class="btn btn-out btn-sm" onclick="comisionesOpenRule(${s.id})">${svg('edit')} Configurar</button></div></article>`).join('');el.innerHTML=`<section class="ven-panel"><div class="ven-panel-head"><div><div class="ven-panel-title">${svg('settings')} Reglas por vendedor</div><div class="ven-panel-sub">Aquí se define la comisión; el perfil operativo continúa en Vendedores</div></div><button class="btn btn-out btn-sm" onclick="routeTo('vendedores')">Administrar vendedores</button></div><div class="ven-panel-body"><div class="ven-search"><span>${svg('search')}</span><input value="${_comEsc(_comQuery)}" oninput="_comQuery=this.value;_comRenderRules(document.getElementById('com-content'))" placeholder="Buscar vendedor…"/></div><div class="com-rule-grid">${cards||_comEmpty('users','No hay vendedores activos','Crea o activa vendedores desde el módulo Vendedores.')}</div></div></section>`;}

function _comRenderFlow(el){const cols=[['borrador','Por revisar','Cálculo todavía editable'],['aprobado','Aprobadas','Disponibles para Nómina'],['pagado','Pagadas','Liquidadas desde Nómina']];el.innerHTML=`<section class="ven-panel"><div class="ven-panel-head"><div><div class="ven-panel-title">${svg('trend')} Flujo de comisiones</div><div class="ven-panel-sub">El estado termina en pagada únicamente cuando Nómina completa el desembolso</div></div><button class="btn btn-green btn-sm" onclick="comisionesOpenCalculation()">${svg('plus')} Calcular</button></div><div class="ven-panel-body"><div class="ven-kanban">${cols.map(([status,title,sub])=>{const runs=_comState.runs.filter(x=>x.status===status);return `<div class="ven-kanban-col"><div class="ven-kanban-head"><div><strong>${title}</strong><span>${sub}</span></div><b>${runs.length}</b></div><div class="ven-kanban-list">${runs.map(r=>`<article class="ven-kanban-card" onclick="comisionesView(${r.id})"><div class="flex between"><strong>${_comEsc(r.salesperson_name)}</strong>${_comBadge(r.status)}</div><div class="txt-xs muted" style="margin-top:6px">${_comEsc(r.date_from)} — ${_comEsc(r.date_to)}</div><div class="ven-kanban-amount">${_comMoney(r.commission_total)}</div><div class="ven-kanban-foot"><span>${_comFrequency(r.frequency)}</span>${status==='borrador'?`<button onclick="event.stopPropagation();comisionesApprove(${r.id})">Aprobar</button>`:status==='aprobado'?'<span>Esperando Nómina</span>':'<span>Pagada</span>'}</div></article>`).join('')||'<div class="ven-kanban-empty">Sin registros</div>'}</div></div>`}).join('')}</div></div></section>`;}

function comisionesOpenRule(id){const s=_comState.sellers.find(x=>Number(x.id)===Number(id));if(!s)return;openModal(`<div class="modal-title">Regla de comisión</div><div class="modal-sub">${_comEsc(s.name)} · esta configuración no modifica su salario de Nómina</div><div class="nom-comp-preview"><div class="ven-avatar ${s.seller_type==='ambulante'?'street':''}">${_comInitials(s.name)}</div><div><strong>${_comEsc(s.code)} · ${s.seller_type==='ambulante'?'Ambulante':'Fijo'}</strong><span>La próxima liquidación utilizará esta regla.</span></div></div><div class="fg"><label class="lbl">Forma de cálculo</label><select class="inp" id="com-rule-mode" onchange="comisionesRuleModeChanged()"><option value="percent_sales" ${s.commission_mode==='percent_sales'?'selected':''}>Porcentaje de venta neta</option><option value="percent_margin" ${s.commission_mode==='percent_margin'?'selected':''}>Porcentaje del margen</option><option value="fixed_sale" ${s.commission_mode==='fixed_sale'?'selected':''}>Monto fijo por venta</option><option value="none" ${s.commission_mode==='none'?'selected':''}>Sin comisión</option></select></div><div class="g2"><div class="fg" data-com-rate><label class="lbl">Porcentaje</label><input class="inp" id="com-rule-rate" type="number" min="0" max="100" step="0.01" value="${Number(s.commission_rate||0)}"/></div><div class="fg" data-com-fixed><label class="lbl">Monto por venta</label><input class="inp" id="com-rule-fixed" type="number" min="0" step="0.01" value="${Number(s.commission_fixed||0)}"/></div></div><div class="fg"><label class="lbl">Frecuencia de liquidación</label><select class="inp" id="com-rule-frequency">${['semanal','quincenal','mensual'].map(x=>`<option value="${x}" ${s.commission_frequency===x?'selected':''}>${_comFrequency(x)}</option>`).join('')}</select></div><div class="ven-callout">Cambiar la regla no altera liquidaciones ya creadas: estas conservan su porcentaje y base histórica.</div><div class="modal-foot"><button class="btn btn-out" onclick="closeModal()">Cancelar</button><button class="btn btn-green" onclick="comisionesSaveRule(${s.id})">${svg('check')} Guardar regla</button></div>`);comisionesRuleModeChanged();}
function comisionesRuleModeChanged(){const mode=document.getElementById('com-rule-mode')?.value;document.querySelectorAll('[data-com-rate]').forEach(x=>x.hidden=!['percent_sales','percent_margin'].includes(mode));document.querySelectorAll('[data-com-fixed]').forEach(x=>x.hidden=mode!=='fixed_sale');}
async function comisionesSaveRule(id){const s=_comState.sellers.find(x=>Number(x.id)===Number(id));if(!s)return;const mode=document.getElementById('com-rule-mode').value,data={...s,commission_mode:mode,commission_rate:['percent_sales','percent_margin'].includes(mode)?document.getElementById('com-rule-rate').value:0,commission_fixed:mode==='fixed_sale'?document.getElementById('com-rule-fixed').value:0,commission_frequency:document.getElementById('com-rule-frequency').value};const r=await window.api.salespeople.update({id,data,requestUserId:user.id});if(!r?.ok){toast(r?.error||'No se pudo guardar la regla','err');return;}closeModal();toast('✓ Regla de comisión actualizada');await renderComisiones(document.getElementById('page'));}

async function comisionesOpenCalculation(sellerId=null){const active=_comState.sellers.filter(s=>s.status==='activo'&&s.commission_mode!=='none');if(!active.length){toast('Configura primero una regla de comisión','w');_comTab='reglas';_comRender();return;}const selected=active.find(x=>Number(x.id)===Number(sellerId))||active[0],period=await window.api.salespeople.suggestedPeriod({salespersonId:selected.id,asOf:_comToday()});openModal(`<div class="modal-title">Calcular liquidación de comisión</div><div class="modal-sub">Este documento es comercial y permanece separado de Nómina hasta su aprobación.</div><div class="fg"><label class="lbl">Vendedor</label><select class="inp" id="com-calc-seller" onchange="comisionesRefreshPeriod()">${active.map(s=>`<option value="${s.id}" ${Number(s.id)===Number(selected.id)?'selected':''}>${_comEsc(s.code)} · ${_comEsc(s.name)} · ${_comEsc(_comMode(s))}</option>`).join('')}</select></div><div class="g2"><div class="fg"><label class="lbl">Desde</label><input class="inp" id="com-calc-from" type="date" value="${period?.data?.from||_comMonthStart()}"/></div><div class="fg"><label class="lbl">Hasta</label><input class="inp" id="com-calc-to" type="date" value="${period?.data?.to||_comToday()}"/></div></div><div id="com-calc-preview" class="com-preview">Calculando ventas comisionables…</div><div class="modal-foot"><button class="btn btn-out" onclick="closeModal()">Cancelar</button><button class="btn btn-out" onclick="comisionesPreview()">Actualizar vista previa</button><button class="btn btn-green" onclick="comisionesGenerate()">${svg('check')} Crear liquidación</button></div>`,'modal-lg');comisionesPreview();}
async function comisionesRefreshPeriod(){const p=await window.api.salespeople.suggestedPeriod({salespersonId:document.getElementById('com-calc-seller').value,asOf:_comToday()});if(p?.ok){document.getElementById('com-calc-from').value=p.data.from;document.getElementById('com-calc-to').value=p.data.to;}comisionesPreview();}
async function comisionesPreview(){const box=document.getElementById('com-calc-preview');if(!box)return;box.innerHTML='Calculando…';const r=await window.api.salespeople.previewCommission({salespersonId:document.getElementById('com-calc-seller').value,from:document.getElementById('com-calc-from').value,to:document.getElementById('com-calc-to').value});if(!r?.ok){box.innerHTML=`<span style="color:var(--red)">${_comEsc(r?.error)}</span>`;return;}const d=r.data;box.innerHTML=`<div><label>Ventas comisionables</label><strong>${d.salesCount} · ${_comMoney(d.salesTotal)}</strong></div><div><label>Margen</label><strong>${_comMoney(d.marginTotal)}</strong></div><div class="primary"><label>Comisión calculada</label><strong>${_comMoney(d.commissionTotal)}</strong></div><p>Regla: ${_comEsc(_comMode(d.seller))}. Las devoluciones vigentes ya fueron descontadas.</p>`;}
async function comisionesGenerate(){const data={salespersonId:document.getElementById('com-calc-seller').value,from:document.getElementById('com-calc-from').value,to:document.getElementById('com-calc-to').value};const r=await window.api.salespeople.generateCommission({data,requestUserId:user.id});if(!r?.ok){toast(r?.error||'No se pudo crear la liquidación','err');return;}closeModal();toast(`✓ Liquidación creada por ${_comMoney(r.data.commissionTotal)}`);_comTab='liquidaciones';await renderComisiones(document.getElementById('page'));}
async function comisionesApprove(id){const r=await window.api.salespeople.approveCommission({id,requestUserId:user.id});if(!r?.ok){toast(r?.error||'No se pudo aprobar','err');return;}toast('✓ Comisión aprobada y disponible para Nómina');await renderComisiones(document.getElementById('page'));}

async function comisionesView(id){const r=await window.api.salespeople.getCommissionById({id});if(!r?.ok||!r.data){toast(r?.error||'Liquidación no encontrada','err');return;}const run=r.data,lines=run.lines||[];openModal(`<div class="modal-title">Liquidación de comisión</div><div class="modal-sub">${_comEsc(run.salesperson_name)} · ${_comEsc(run.date_from)} al ${_comEsc(run.date_to)} · ${_comBadge(run.status)}</div><div class="com-detail-metrics"><div><label>Ventas</label><strong>${_comMoney(run.sales_total)}</strong></div><div><label>Margen</label><strong>${_comMoney(run.margin_total)}</strong></div><div><label>Operaciones</label><strong>${lines.length}</strong></div><div class="primary"><label>Comisión</label><strong>${_comMoney(run.commission_total)}</strong></div></div><div class="tw"><table><thead><tr><th>Fecha / referencia</th><th>Cliente</th><th>Origen</th><th style="text-align:right">Venta</th><th style="text-align:right">Base</th><th style="text-align:right">Comisión</th></tr></thead><tbody>${lines.map(line=>`<tr><td><strong>${_comEsc(line.sale_date)}</strong><div class="ven-person-meta">${_comEsc(line.reference||'Sin referencia')}</div></td><td>${_comEsc(line.customer_name||'Consumidor Final')}</td><td><span class="badge n">${line.source_type==='sistema'?'POS':'Externa'}</span></td><td style="text-align:right" class="ven-money">${_comMoney(line.sale_amount)}</td><td style="text-align:right" class="ven-money">${_comMoney(line.commission_base)}</td><td style="text-align:right;font-weight:800;color:#7c3aed" class="ven-money">${_comMoney(line.commission_amount)}</td></tr>`).join('')}</tbody></table></div><div class="modal-foot"><button class="btn btn-out" onclick="closeModal()">Cerrar</button>${run.status==='borrador'?`<button class="btn btn-green" onclick="closeModal();comisionesApprove(${run.id})">${svg('check')} Aprobar liquidación</button>`:''}${run.status==='aprobado'?'<button class="btn btn-out" onclick="closeModal();routeTo(\'nomina\')">Abrir Nómina →</button>':''}</div>`,'modal-xl');}
